//
// Created by Tharuka Devendra on 23/08/2020.
//

#ifndef ALGORITHMS_DFSITERATIVEFORALLPATHS_H
#define ALGORITHMS_DFSITERATIVEFORALLPATHS_H


void testDfsIterativeForAllPaths();

#endif //ALGORITHMS_DFSITERATIVEFORALLPATHS_H
